name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # تشغيل كل يوم في منتصف الليل
  workflow_dispatch: # يسمح بالتشغيل اليدوي

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.email "kasemsafwat.96@gmail.com"
          git config --global user.name "kasemsafwat"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/hazemr2121/Npathways.git || git remote set-url upstream https://github.com/hazemr2121/Npathways.git
          git fetch upstream

      - name: Checkout Main Branch
        run: |
          git checkout -B main origin/main

      - name: Merge Upstream Changes
        run: |
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push Changes to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kasemsafwat/Npathways.git main
